# Generated by Django 2.0.13 on 2019-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moresysapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieid',
            new_name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.FloatField(),
        ),
    ]
